# Generated by Django 4.2.2 on 2023-06-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatransfer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='account_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='filename_to_transfer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
