# Generated by Django 4.2.2 on 2023-06-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datatransfer', '0003_project_date_create_alter_project_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ssh_key',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
